# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Charlie Ann Page
email: me@charlieannpage.co.uk
description: Charlie Ann Page is a consultant and freelancer. She has a broad range of skills, including in education and training, AI, modelling & simulation, and game design and development. She trades through her limited company, Another Feather Limited.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://charlieannpage.co.uk" # the base hostname & protocol for your site
twitter_username: C_A__Page

# Build settings
markdown: kramdown

header_pages:
- index.md
- teaching.md
- elearning.md
- simulation.md
- games.md
- ai.md
- Contact.md
